name: lcov-cop
author: felangel
description: 'Enforce LCOV Coverage Thresholds'
branding:
  icon: 'code'
  color: green
inputs:
  path:
    description: 'lcov path'
    required: true
  min_coverage:
    description: 'minimum coverage percentage allowed'
    required: true
    default: 100
  exclude:
    description: 'paths to exclude from coverage'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}
    - ${{ inputs.min_coverage }}
    - ${{ inputs.exclude }}